### ISSUE TITLE
Section 3-4 exercises rethink

### ISSUE THREAD

**Issue by anenadic** [softwaresaved/az-intermediate-software-skills-course#85]
A few problems were identified with exercises that learners start working on in section 3 individually (to implement a new requirement) and carry on in section 4 in team work (to add tests to the new requirement):
- people may not have implemented the new requirement exercise and there is no solution provided so there was not enough code to carry on working in teams - a reference solution that people can copy paste could solve this issue
- there is a number of branches that learners have in their repos that may cause confusion - main, develop, feature-x they implemented in section 3 and feature-x-tests that a team member needs to add in section 4 to enable practicing code review and making PRs. Not sure much can be done here apart from explaining things better and perhaps drawing a diagram of branches
- in between these two exercises, at the end of section 3 in Architecture revisited episode, there is an exercise to add a new view to the code and use argument parsing more extensively - this episode needs a bit more explanation on argument parsing 
- the material is intended for self-learning but exercises in section 4/5 rely on team work - we should make sure we cover scenarios where people work on their own too

A few issues related to this bigger issue have already been reported and will help with solving this:
- [ ] Code review episode rework (issue #69 )
- [ ] Rework of exercises on implementing requirements (issue #48 and #49)
- [ ] Better explanation for argument passing (#61) and making sure that all exercises flow from Section 3 to Section 4
- [ ] An extra exercise in Architecture, revisited episode (issue #37 )
- [ ] Making sure that exercises can be done both in teams and individually
